# -*- coding: utf-8 -*-
"""Task_Session-25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IVtnVFIMAlhKgoeZ75PZVaYJ24xw69t
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

"""### `Q-1:` Using Gapminder Data
1. Create a scatter plot of 'gdpPercap' against 'lifeExp' for the year 2007, with the size of the markers determined by 'pop' and the color determined by 'continent'.
"""

import plotly.express as px
df = px.data.gapminder()
df.head()

temp_df = df[df['year']==2007]

sns.relplot(kind='scatter', data=temp_df, x='gdpPercap', y='lifeExp', size='pop', hue='continent')

"""### `Q-2-3:` Using `flights` dataset of seaborn.

2. Using the "flights" dataset that comes with seaborn, create a heatmap that shows the average number of passengers per month for each year.

3. Using the seaborn's flight dataset, create a clustermap to visualize the relationship between the number of passengers, months, and year.

"""

df = sns.load_dataset('flights')
df.head()

temp_df = df.pivot_table(index='month',columns='year',values='passengers', aggfunc='mean')

sns.heatmap(temp_df)

sns.clustermap(temp_df)

"""## For questions 4-8:

For these qestions, an insurance dataset is used. You can get details from [here](https://www.kaggle.com/datasets/thedevastator/insurance-claim-analysis-demographic-and-health). And if you want this dataset to use directly, then you can use this link: **https://docs.google.com/spreadsheets/d/e/2PACX-1vQVpcVtdYdZU4zU4-lqxt-iPHkyndDWs_aqEDUu9ZodlJ48Dku0PFgdXlj2N5RCmwXJrNtZLsI_wEVf/pub?gid=220677750&single=true&output=csv**

### **`Q-4:`** Draw a scatter plot based on the below conditions:
1. x-axis should be "age" and y-axis should be "bmi".
2. For hue, size and style parameters use "diabetic", "gender" and "smoker" column respectively.
3. Add title to your chart.
4. Age should be less than 70 percentiles.
5. BMI should be greater than the average value of the filtered age dataset.
"""

df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQVpcVtdYdZU4zU4-lqxt-iPHkyndDWs_aqEDUu9ZodlJ48Dku0PFgdXlj2N5RCmwXJrNtZLsI_wEVf/pub?gid=220677750&single=true&output=csv')

df['age'].unique()

df.dropna(inplace=True)

df = df[df['age']<df['age'].quantile(0.70)]

round(df['age'].mean(),2)

temp_df = df[df['bmi']>round(df['age'].mean(),2)]

sns.relplot(kind='scatter', data=temp_df, x='age', y='bmi', hue='diabetic', size='gender', style='smoker')
plt.title('age vs bmi')
plt.show()

"""### **`Q-5:`** Draw a line plot by using the below informations

1. bloodpressure vs children
2. Blood-pressure values should be between 90 and 100. The upper and lower limit are included.
3. Show the details of "smoker".
"""

temp_df = df[(df['bloodpressure']>=90) & (df['bloodpressure']<=100)]

sns.relplot(kind="line", data = temp_df, x='bloodpressure', y='children', hue='smoker', err_style=None)
plt.show()

"""### **`Q-6:`** Draw a histogram using displot

- based on "age" column.
- Show details of "smoker" (hue).
- Create 2 separate charts for the above 2 conditions based on "gender" side-by-side.
"""

sns.displot(kind='hist', data=df, x='age', hue='smoker', col='gender')

"""### **`Q-7:`** Draw a kde plot between "age" and "bloodpressure"."""

sns.displot(data=df, kind='kde', x='age', y='bloodpressure')

"""### **`Q-8:`** Draw a clustermap between between "age", "bmi" and "bloodpressure"."""

df.head()

sns.clustermap(df[["age", "bmi", "bloodpressure"]])

